/*
 * PlayerView.java
 *
 * Created on __DATE__, __TIME__
 */

package ui.player;

/**
 * 
 * @author __USER__
 */
public class PlayerView extends javax.swing.JFrame {

	/** Creates new form PlayerView */
	public PlayerView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButtonAdd = new javax.swing.JButton();
		jButtonUpdate = new javax.swing.JButton();
		jButtonDelete = new javax.swing.JButton();
		jButtonSearchGroup = new javax.swing.JButton();
		jButtonSearchComplex = new javax.swing.JButton();
		jButtonBack = new javax.swing.JButton();

		// setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7403\u5458\u7ba1\u7406");

		jButtonAdd.setText("\u6dfb\u52a0\u7403\u5458");
		jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAddActionPerformed(evt);
			}
		});

		jButtonUpdate.setText("\u7403\u5458\u53d8\u66f4");
		jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonUpdateActionPerformed(evt);
			}
		});

		jButtonDelete.setText("\u5220\u9664\u7403\u5458");
		jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonDeleteActionPerformed(evt);
			}
		});

		jButtonSearchGroup
				.setText("\u5206\u7c7b\u67e5\u8be2\u7403\u5458\u4fe1\u606f");
		jButtonSearchGroup
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonSearchGroupActionPerformed(evt);
					}
				});

		jButtonSearchComplex
				.setText("\u590d\u5408\u6761\u4ef6\u67e5\u8be2\u7403\u5458\u4fe1\u606f");
		jButtonSearchComplex
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonSearchComplexActionPerformed(evt);
					}
				});

		jButtonBack.setText("\u8fd4\u56de");
		jButtonBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonBackActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(142,
																		142,
																		142)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButtonDelete,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						109,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonUpdate,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						109,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonAdd,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						109,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(104,
																		104,
																		104)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButtonSearchGroup,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						177,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonSearchComplex,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						177,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(143,
																		143,
																		143)
																.addComponent(
																		jButtonBack,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		109,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(113, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(8, 8, 8)
								.addComponent(jButtonAdd,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButtonUpdate,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButtonDelete,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(12, 12, 12)
								.addComponent(jButtonSearchGroup,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButtonSearchComplex,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButtonBack,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(25, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>
		// GEN-END:initComponents

	private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void jButtonSearchComplexActionPerformed(
			java.awt.event.ActionEvent evt) {
		(new SearchPlayer(null, true)).setVisible(true);
	}

	private void jButtonSearchGroupActionPerformed(
			java.awt.event.ActionEvent evt) {
		(new DisplayPlayer()).setVisible(true);
	}

	private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		(new DeletePlayer()).setVisible(true);
	}

	private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {
		(new UpdatePlayer()).setVisible(true);
	}

	private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {
		(new AddPlayer()).setVisible(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PlayerView().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonAdd;
	private javax.swing.JButton jButtonBack;
	private javax.swing.JButton jButtonDelete;
	private javax.swing.JButton jButtonSearchComplex;
	private javax.swing.JButton jButtonSearchGroup;
	private javax.swing.JButton jButtonUpdate;
	// End of variables declaration//GEN-END:variables

}